language: java
jdk:
  - openjdk8

# 설정한 브랜치(master)가 push될때 Travis CI 수행
branches:
  only:
    - master

# Travis CI 서버의 Home
# gradle을 통해 받은 의존성을 디렉토리에 캐싱하여 이후 중복되지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시될때 수행할 명령어
# 프로젝트 내부 gradlew을 통해 clean & build수행
script: "./gradlew clean build"

# deploy가 실행되기 전에 수행할 내용
# 현재위치의 모든파일을 압축하여 새 디렉토리를 생성하고 압축파일을 이동시킴
before_deploy:
  - zip -r joohyung-springboot-webservice *
  - mkdir -p deploy
  - mv joohyung-springboot-webservice.zip deploy/joohyung-springboot-webservice.zip

# before_deploy때 생성한 deploy 디렉토리 내 파일들을 S3로 전송
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: joohyung-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: joohyung-springboot-build
    key: joohyung-springboot-webservice.zip
    build-type: zip
    application: joohyung-springboot-webservice
    deployment-group: joohyung-springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 자동으로 메일로 알림
notifications:
  email:
    # recipients: "i009727@kyonggi.ac.kr"
    recipients: "i00960910@gmail.com"