language: java
jdk:
  - openjdk8

# 설정한 브랜치(master)가 push될때 Travis CI 수행
branches:
  only:
    - master

# Travis CI 서버의 Home
# gradle을 통해 받은 의존성을 디렉토리에 캐싱하여 이후 중복되지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시될때 수행할 명령어
# 프로젝트 내부 gradlew을 통해 clean & build수행
script: "./gradlew clean build"

# CI 실행 완료시 자동으로 메일로 알림
notifications:
  email:
    recipients: "i009727@kyonggi.ac.kr"