version: 0.0        # codedeploy의 버전정보d
os: linux
files:
  - source: /       # codedeploy로 부터 받은 파일중 destination으로 전달할 대상(/: 전체파일)
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes  # 덮어쓰기 옵션

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh   # nginx와 연결되어 있지 않은 springboot 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh  # nginx와 연결되어 있지 않은 port로 새로운 버전의 springboot 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새로운 springboot가 정상 실행되는지 확인
      timeout: 60
      runas: ec2-user